app/sigmemories/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, BooleanField, SubmitField, ValidationError, TextField, TextAreaField, SelectField
from wtforms.validators import DataRequired, Email, Length, EqualTo
from ..models import User, Sigmemories, DiplomeesSigma
from wtforms_sqlalchemy.fields import QuerySelectField


class Dedicace(FlaskForm):
    diplomee = QuerySelectField('Diplomé(e)', blank_text='Sélectionnez le futur diplômé', allow_blank=True,
                                query_factory=lambda: DiplomeesSigma.query.order_by(DiplomeesSigma.nom).all() )
    surnom1 = TextField('surnom 1')
    surnom2 = TextField('surnom 2')
    surnom3 = TextField('surnom 3')
    ipq1 = TextField('IPQ 1')
    ipq2 = TextField('IPQ 2')
    ipq3 = TextField('IPQ 3')
    deviendra = TextField('Deviendra')
    souvenir = TextField('Mon meilleur souvenir avec')
    expression = TextField('Son expression favorite')
    imbattable = TextField('Est imbattable pour')
    dedicace = TextAreaField('Dédicace', render_kw={"rows": 3, "cols": 100})
    submit = SubmitField()


class ModDedicace(FlaskForm):
    surnom1 = TextField('surnom 1')
    surnom2 = TextField('surnom 2')
    surnom3 = TextField('surnom 3')
    ipq1 = TextField('IPQ 1')
    ipq2 = TextField('IPQ 2')
    ipq3 = TextField('IPQ 3')
    deviendra = TextField('Deviendra')
    souvenir = TextField('Mon meilleur souvenir avec')
    expression = TextField('Son expression favorite')
    imbattable = TextField('Est imbattable pour')
    dedicace = TextAreaField('Dédicace', render_kw={"rows": 3, "cols": 100})
    submit = SubmitField()


# Temporary fix for ValueError with SQLAlchemy 1.2 see https://github.com/wtforms/wtforms-sqlalchemy/issues/9
import wtforms_sqlalchemy.fields as f  # noqa


def get_pk_from_identity(obj):
    cls, key = f.identity_key(instance=obj)[:2]
    return ':'.join(f.text_type(x) for x in key)


f.get_pk_from_identity = get_pk_from_identity

app/sigmemories/routes.py
from flask import render_template, redirect, request, url_for, flash, Blueprint, current_app
from flask_login import login_user, logout_user, login_required, current_user
from .. import db
from ..models import User, Sigmemories, DiplomeesSigma
from .forms import Dedicace, ModDedicace

bp = Blueprint('private', __name__, template_folder='templates')


@bp.route('/newdedi', methods=['GET', 'POST'])
@login_required
def new_dedi():
    form = Dedicace(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            if form.diplomee.data:
                dedi = Sigmemories(diplome=form.diplomee.data.id)
                dedi.ipq1 = form.ipq1.data
                dedi.ipq2 = form.ipq2.data
                dedi.ipq3 = form.ipq3.data
                dedi.surnom1 = form.surnom1.data
                dedi.surnom2 = form.surnom2.data
                dedi.surnom3 = form.surnom3.data
                dedi.expression = form.expression.data
                dedi.inbattable = form.imbattable.data
                dedi.souvenir = form.souvenir.data
                dedi.deviendra = form.deviendra.data
                dedi.dedicace = form.dedicace.data
                dedi.id_auteur = current_user.get_id()
                db.session.add(dedi)
                db.session.commit()
                flash('Tag ajouté !', 'success')
                return redirect(url_for('private.listdedi'))
            else:
                flash('Veuillez sélectionner un diplômé', 'error')
    return render_template("dedicasse.html", form=form, title='Sigmemories')


def query_diplomee():
    diplos = DiplomeesSigma.query.all()
    tuple_list = []
    for diplo in diplos:
        element = (diplo.id, diplo)
        tuple_list.append(element)
    return tuple_list


@bp.route('/moddedi/<id>', methods=['GET', 'POST'])
@login_required
def moddedi(id):
    dedi = Sigmemories.query.filter_by(id=id).first()
    diplo = DiplomeesSigma.query.filter_by(id=dedi.id_diplome).first()
    nom_diplo = diplo
    form = ModDedicace(request.form)
    if request.method == 'GET':
        form.ipq1.data = dedi.ipq1
        form.ipq2.data = dedi.ipq2
        form.ipq3.data = dedi.ipq3
        form.surnom1.data = dedi.surnom1
        form.surnom2.data = dedi.surnom2
        form.surnom3.data = dedi.surnom3
        form.expression.data = dedi.expression
        form.imbattable.data = dedi.inbattable
        form.souvenir.data = dedi.souvenir
        form.deviendra.data = dedi.deviendra
        form.dedicace.data = dedi.dedicace
    if request.method == 'POST':
        if form.validate_on_submit():
                dedi.ipq1 = form.ipq1.data
                dedi.ipq2 = form.ipq2.data
                dedi.ipq3 = form.ipq3.data
                dedi.surnom1 = form.surnom1.data
                dedi.surnom2 = form.surnom2.data
                dedi.surnom3 = form.surnom3.data
                dedi.expression = form.expression.data
                dedi.inbattable = form.imbattable.data
                dedi.souvenir = form.souvenir.data
                dedi.deviendra = form.deviendra.data
                dedi.dedicace = form.dedicace.data
                dedi.id_auteur = current_user.get_id()
                db.session.add(dedi)
                db.session.commit()
                print('ok')
                flash('Tag édité !', 'success')
                return redirect(url_for('private.listdedi'))
    return render_template("moddedi.html", form=form, title='Sigmemories', diplo=diplo)


@bp.route('/deldedi/', methods=['GET', 'POST'])
@login_required
def deldedi():
    id = request.form['id'] # To get id provided by JS 
    dedi = Sigmemories.query.get_or_404(id)
    db.session.delete(dedi)
    db.session.commit()
    flash('Suppresion du tag faite')
    return redirect(url_for('private.listdedi'))


@bp.route('/sigmemories')
@login_required
def listdedi():
    dedicaces_faites = Sigmemories.query.filter_by(
        id_auteur=current_user.get_id()).all()
    dedi_diplo = dict()
    for dedi in dedicaces_faites:
        diplo = DiplomeesSigma.query.filter_by(
            id=dedi.id_diplome).first()
        dedi_diplo[dedi] = diplo
    return render_template('sigmemories.html', dedi_diplo=dedi_diplo)

app/sigmemories/templates/dedicasse.html
{% extends "_base2.html" %} 
{% import "wtf.html" as wtf %} 
{% block app_content %}

<div class="py-5 section-aquamarine">
    <div class="container">
        <div class="row">
            <div class="col-md-12 my-4">
                <h1 class="text-light">Écrire un Sigmemory à un diplomé</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                {{ wtf.quick_form(form) }}
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/sigmemories/templates/moddedi.html
{% extends "_base2.html" %} {% import "wtf.html" as wtf %} {% block app_content %}

<div class="py-5 section-aquamarine">
    <div class="container">
        <div class="row">
            <div class="col-md-12 my-4">
                <h1 class="text-light">Modifier le Sigmemory de <strong>{{ diplo }}</strong</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                {{ wtf.quick_form(form) }}
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/sigmemories/templates/sigmemories.html
{% extends "_base2.html" %} {% import "wtf.html" as wtf %} {% block app_content %}
<div class=" py-5">
    <div class="container">

        {% if dedi_diplo %}
        <table class="my-2 table table-hover">
            <thead>
                <tr>
                    <th>Diplomé</th>
                    <th>Dédicace</th>
                    <th width=15%>Modifier tag</th>
                    <th width=15%>Supprimer tag</th>
                </tr>
            </thead>

            <tbody>
                {% for dedi, diplo in dedi_diplo.items() %}
                <tr>
                    <td>{{ diplo.nom + " " + diplo.prenom }} </td>
                    <td>{{ dedi.dedicace }}</td>
                    <td>
                        <a href="{{ url_for('private.moddedi', id=dedi.id) }}">
                            <i class="fas fa-pencil-alt"></i> Modifier</a>
                    </td>
                    <td>
                        <a data-id={{ dedi.id }} onclick="ConfirmDelete(this)" ><i class="fas fa-trash-alt"></i> Supprimer</a>
                    </td>

                </tr>
                {% endfor %}
            </tbody>

        </table>
        {% else %}
        <p class="my-4">Pas de tag écrit :(</p>
        {% endif %}
        <a href="{{ url_for('private.new_dedi') }}" class="btn btn-default btn-lg">
            <i class="fa fa-plus"></i>
            Faire un nouveau tag
        </a>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Voulez-vous supprimer cette sigmemories ?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                <button type="button" class="btn btn-primary" onclick="Delete()">Supprimer</button>
            </div>
        </div>
    </div>
</div>
<script>
    function ConfirmDelete(elem) {
        localStorage.setItem('deleteId', $(elem).attr('data-id'));
        $('#deleteModal').modal();
    }

    function Delete() {
        $.ajax({
            url: '/deldedi/',
            data: {
                id: localStorage.getItem('deleteId')
            },
            type: 'POST',
            success: function (res) {
            $('#deleteModal').modal('hide');
            location.reload();  
        }});
    }

</script>
{% endblock %}